export const JOB: any[] = [
  {
    JobID: 1,
    JobTitle: "React Developer 1",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "Etown3 KCN Q9",
    Contact: " Khu CNC  Long Thanh My Q9 TP Thu Duc",
  }, {
    JobID: 2,
    JobTitle: "React Developer 2 ",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  }, {
    JobID: 3,
    JobTitle: "React Developer 3 ",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 4,
    JobTitle: "React Developer 4",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 5,
    JobTitle: "React Developer 5",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 6,
    JobTitle: "React Developer 6",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 7,
    JobTitle: "React Developer 7",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 8,
    JobTitle: "React Developer 8",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 9,
    JobTitle: "React Developer 9",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  }, {
    JobID: 10,
    JobTitle: "React Developer 10",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  }, {
    JobID: 11,
    JobTitle: "React Developer 11",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 12,
    JobTitle: "React Developer 12",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 13,
    JobTitle: "React Developer 13",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 14,
    JobTitle: "React Developer 14",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 15,
    JobTitle: "React Developer 15",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  },
  {
    JobID: 16,
    JobTitle: "React Developer 16",
    Salary: 265.99,
    CompanyName: "FPT",
    TimeOut: new Date("2023-07-27"),
    JobDescription: "Develop a Websit",
    JobRequirement: "4 years of experience",
    Location: "FPT",
    Contact: "Etown5 Khu CNC HCM",
  }
]
